  $( function() {
    var cities = [
      "Hyderabad" ,
     "Vishakhapatnam",
     "Vijayawada ",
     "Guntur",
     "Warangal", 
     "Rajahmundry",
   "Nellore ",
     "Kakinada",
     "Nizamabad",
     "Kurnool",
     "Ramagundam",
     "Eluru",
     "Kukatpalle",
     "Anantapur",
     "Tirupati",
     "Secunderabad",
     "Vizianagaram",
     "Machilipatnam (Masulipatam)",
     "Lalbahadur Nagar",
     "Karimnagar",
     "Tenali",
     "Adoni",
     "Proddatur",
     "Chittoor",
     "Khammam",
     "Malkajgiri",
     "Cuddapah",
     "Bhimavaram",
     "Nandyal",
     "Mahbubnagar",
     "Guntakal",
     "Qutubullapur",
     "Hindupur",
     "Gudivada",
    "Ongole",
     "Guwahati (Gauhati)",
     "Dibrugarh",
     "Silchar",
     "Nagaon", 
     "Patna", 
     "Gaya",
     "Bhagalpur",
     "Muzaffarpur",
     "Darbhanga",
     "Bihar Sharif",
     "Arrah (Ara)",
     "Katihar", 
     "Munger (Monghyr)",
    "Chapra",
     "Sasaram",
     "Dehri",
     "Bettiah",
    "Chandigarh",
    "Raipur",
     "Bhilai",
     "Bilaspur",
     "Durg",
     "Raj Nandgaon",
     "Korba",
     "Raigarh",
     "Delhi",
     "New Delhi",
     "Delhi Cantonment",
     "Ahmedabad",
     "Surat",
     "Vadodara (Baroda)",
     "Rajkot",
     "Bhavnagar",
     "Jamnagar",
     "Nadiad", 
     "Bharuch (Broach)",
     "Junagadh",
     "Navsari",
     "Gandhinagar",
     "Veraval", 
     "Porbandar",
     "Anand",
     "Surendranagar",
    "Gandhidham",
    "Bhuj",
     "Godhra",
     "Libyan dinar",
     "Patan",
     "Morvi ",
     "Vejalpur", 
     "Faridabad",
     "Rohtak",
     "Panipat",
     "Karnal ",
     "Hisar (Hissar)",
     "Yamuna Nagar ", 
     "Sonipat (Sonepat) ",
     "Gurgaon",
     "Sirsa",
     "Ambala ",
     "Bhiwani ",
     "Ambala Sadar ",
     "Srinagar",
     "Jammu",
     "Ranchi ",
     "Jamshedpur ",
     "Bokaro Steel City ",
     "Dhanbad ",
     "Purnea (Purnia) ",
     "Mango",
     "Hazaribag",
     "Purulia ",
     "Bangalore ",
     "Hubli-Dharwad ",
     "Mysore ",
     "Belgaum",
     "Gulbarga ",
     "Mangalore ",
     "Davangere",
     "Bellary",
     "Bijapur", 
     "Shimoga ",
     "Raichur ",
     "Tumkur ", 
     "Gadag Betigeri ",
     "Mandya",
     "Bidar ",
     "Hospet ",
     "Cochin (Kochi)" ,
     "Thiruvananthapuram (Trivandrum",
     "Calicut (Kozhikode) ",
     "Allappuzha (Alleppey)",
     "Kollam (Quilon)", 
     "Palghat (Palakkad)",
   "Tellicherry (Thalassery) ",
     "Indore",
     "Bhopal",
     "Jabalpur ",
     "Gwalior",
     "Ujjain",
     "Sagar",
     "Ratlam",
     "Burhanpur",
     "Dewas",
     "Murwara (Katni)",
     "Satna",
     "Morena",
     "Khandwa",
     "Rewa",
     "Bhind",
     "Shivapuri",
     "Guna",
     "Mandasor",
     "Damoh",
     "Chhindwara",
     "Vidisha",
     "Mumbai (Bombay)",
     "Nagpur",
     "Pune",
     "Kalyan",
     "Thane (Thana)",
     "Nashik (Nasik)",
    "Solapur (Sholapur)",
     "Shambajinagar (Aurangabad)",
     "Pimpri-Chinchwad",
     "Amravati",
     "Kolhapur", 
     "Bhiwandi", 
     "Ulhasnagar",
     "Malegaon",
     "Akola",
     "New Bombay",
     "Dhule (Dhulia) ",
     "Nanded (Nander) ",
     "Jalgaon", 
     "Chandrapur ",
    "Ichalkaranji",
     "Latur",
     "Sangli",
     "Parbhani",
    "Ahmadnagar",
    "Mira Bhayandar",
     "Jalna",
     "Bhusawal",
     "Miraj",
     "Bhir (Bid)",
     "Gondiya",
     "Yeotmal (Yavatmal)",
     "Wardha",
     " Achalpur",
     "Satara",
     "Imphal",
     "Shillong",
     "Aizawl ",
     "Bhubaneswar",
     "Kataka (Cuttack)",
     "Raurkela",
     "Brahmapur", 
     "Raurkela Civil Township",
     "Sambalpur",
     "Puri",
     "Pondicherry",
     "Ludhiana", 
     "Amritsar",
     "Jalandhar (Jullundur)",
     "Patiala",
    "Bhatinda (Bathinda)",
    "Pathankot",
     "Hoshiarpur",
     "Moga ",
     "Abohar",
     "Lahore ",
     "Faisalabad", 
     "Rawalpindi",
     "Multan",
     "Gujranwala",
     "Sargodha ",
     "Sialkot ",
     "Bahawalpur ", 
     "Jhang  ",
     "Sheikhupura",
     "Gujrat",
     "Kasur ",
     "Rahim Yar Khan ",
     "Sahiwal  ",
     "Okara",
     "Wah",
     "Dera Ghazi Khan ",
     "Chiniot ",
     "Kamoke ",
     "Mandi Burewala ",
     "Jhelum  ",
     "Sadiqabad",
     "Khanewal",
     "Hafizabad ",
     "Muzaffargarh ",
     "Khanpur ",
     "Gojra ",
     "Bahawalnagar",
     "Muridke ",
     "Pak Pattan ",
     "Jaranwala",
     "Chishtian Mandi",
     "Daska", 
     "Mandi Bahauddin ",
     "Ahmadpur East ",
     "Kamalia ", 
     "Vihari  ",
     "Wazirabad",
     "Jaipur" ,
     "Jodhpur",
     "Kota ",
     "Bikaner",
     "Ajmer", 
     "Udaipur",
   "Alwar ",
     "Bhilwara",
     "Ganganagar",
     "Bharatpur",
     "Sikar",
     "Pali",
     "Beawar",
     "Tonk",
     "Chennai (Madras)",
     "Madurai",
"Coimbatore     ",
     "Tiruchirapalli",
     "Salem",
     "Tiruppur (Tirupper)",
     "Ambattur",
     "Thanjavur",
     "Tuticorin",
     "Nagar Coil",
     "Avadi",
     "Dindigul",
     "Vellore",
     "Tiruvottiyur",
     "Erode",
     "Cuddalore",
     "Kanchipuram",
     "Kumbakonam",
     "Tirunelveli",
    "Alandur",
     "Neyveli ",
     "Rajapalaiyam",
     "Pallavaram",
     "Tiruvannamalai", 
     "Tambaram", 
     "Valparai",
     "Bhagalpur",
     "Pudukkottai",
     "Palayankottai",
     "Agartala ",
     "Kanpur ",
     "Lucknow", 
     
    "Varanasi (Benares)",
     "Agra",
     "Allahabad",
     "Meerut",
    "Bareilly",
    "Gorakhpur",
     "Aligarh",
     "Ghaziabad",
     "Moradabad",
     "Saharanpur",
     "Jhansi",
     "Rampur",
     "Muzaffarnagar",
     
     "Shahjahanpur",
     "Mathura",
   
     "Firozabad",
     "Farrukhabad-cum-Fatehgarh",
     "Mirzapur-cum-Vindhyachal",
     "Sambhal", 
    
     "Noida",
     "Hapur",
     "Amroha",
     "Maunath Bhanjan", 
     "Jaunpur",
     "Bahraich",
     "Rae Bareli",
    "Bulandshahr",
    "Faizabad",
     "Etawah",
     "Sitapur",
     "Fatehpur",
     "Budaun ",
     "Hathras", 
     "Unnao",
     "Pilibhit",
     "Gonda",
     "Modinagar ",
     "Orai ",
     "Banda ", 
     " Meerut Cantonment ",
     "Kanpur Cantonment",
     "Dehra Dun",
     "Hardwar (Haridwar) ",
     "Haldwani-cum-Kathgodam ",
     "Calcutta [Kolkata] ",
     "Haora (Howrah)",
     "Durgapur",
     "Bhatpara ",
     "Panihati ",
     "Kamarhati",
     "Asansol ",
     "Barddhaman (Burdwan)",
     "Barahanagar (Baranagar)",
     "Siliguri (Shiliguri)",
     "Bally ",
     "Kharagpur ",
     
     "Burnpur ",
     "Uluberia",
     "Hugli-Chinsurah ",
     "Raiganj ",
     "North Dum Dum",
     "Dabgram",
     "Ingraj Bazar (English Bazar)", 
     "Serampore ",
     "Barrackpur ",
     "Naihati ", 
     "Midnapore (Medinipur) ",
     "Navadwip",
     "Krishnanagar ",
     "Chandannagar ",
   
     
     
     "Balurghat",
     "Berhampore (Baharampur)",
     "Bankura ",
     "Titagarh",
     "Halisahar",
     "Santipur",
     "Kulti-Barakar",
     "Barasat",
     "Rishra",
     "Basirhat",
     "Uttarpara-Kotrung",
     "North Barrackpur",
     "Haldia",
     "Habra",
     "Kanchrapara",
     "Champdani",
     "Ashoknagar-Kalyangarh",
     "Bansberia",
     "Baidyabati",
     "Hassan"
    ];
    $( "#autocomplete" ).autocomplete({
      source: cities
    });
  } );
  